version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/<your-app-directory>  # Adjust path as per your repo
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
