on:
  push:
    branches:
      - master  # Trigger deployment on push to 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.USER }}@${{ secrets.IP }} << 'EOF'
            # Navigate to the application directory
            cd /home/ubuntu/python-app || exit

            # Pull the latest code
            git pull origin master

            # Setup Python virtual environment and install dependencies
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

            # Kill previous app if running
            pkill -f "python src/app.py" || true

            # Run your app in the background
     