on:
  push:
    branches:
      - master  # Trigger deployment on push to 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the application directory
            cd /home/ubuntu/test-ec2 || exit
      
            # Pull the latest code
            git pull
      
            # Setup Python virtual environment and install dependencies
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      
            # Kill previous app if running
            pkill -f "python src/app.py" || true
      
            # Run your app in the background
            nohup python src/app.py &
